[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
# known_absolute = "<PACKAGE_NAME>"
# sections = ["FUTURE","STDLIB","THIRDPARTY","ABSOLUTE","LOCALFOLDER"]
sections = ["FUTURE","STDLIB","THIRDPARTY","LOCALFOLDER"]
line_length = 120

[tool.mypy]
follow_imports = "normal"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
warn_unreachable = true
strict_equality = true
